[workspace]
resolver = "2"
members = ["interpreter", "lexer", "parser"]

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
panic = "deny"
