[package]
name = "repl"
version = "0.1.0"
edition = "2024"

[dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
interpreter = { path = "../interpreter" }
regex = "1.12.2"

[lints]
workspace = true
