[package]
name = "lang"
version = "0.1.0"
edition = "2024"

[dependencies]
compiler = { path = "../compiler" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
transpiler = { path = "../transpiler" }

[lints]
workspace = true
